.TH FINFAKTURA 1 "2015-10-24" "" "Invoice Manager (Norway)"

.SH NAME
finfaktura \- Create and manage invoices (Norwegian specs)

.SH SYNOPSIS
usage: faktura [-i] [-d] [-v] [-h]

.SH DESCRIPTION
Creates PDF invoices for use in Norway. Automatic email submission and backup.

By default, the program starts up with a Qt4 gui.

 -i starts in interactive, non-gui mode.
 -d starts in debug mode, with a lot of messages printed on the console
 -v shows the finfaktura version and exits
 -h shows some help and exits.

Requires python and some python extensions: PyQt4 (package name python-qt4) and reportlab (python-reportlab).

.SH SEE ALSO
Some docs are installed under /usr/share/doc/finfaktura. The project lives on the web at http://sourceforge.net/projects/finfaktura/

.SH AUTHOR
Håvard Gulldahl <havard@gulldahl.no>.
Modified by Johnny A. Solbu <johnny@solbu.net>

.SH Project Manager
Johnny A. Solbu <johnny@solbu.net>

.SH BUGS
Bugs can be reported at: https://sourceforge.net/p/finfaktura/tickets/

\# This groff man page (C) 2006-2008 Håvard Gulldahl, GPLv2 Licenced.
\# $Id$
